config:
  send_anonymous_usage_stats: False
  use_colors: True
  partial_parse: True

jaffle_shop:
  outputs:
    dev:
      type: postgres
      threads: 1
      host: "{{ env_var('DBT_HOST') }}"
      port: 6432
      user: "{{ env_var('DBT_USER') }}"
      pass: "{{ env_var('DBT_PASSWORD') }}"
      dbname: otus-hw
      schema: dbt
  target: dev  